# MLB top pitchers Analysis (2010-2019)

### all pitchers

In [2]:
import os
import pandas as pd
import matplotlib.pyplot as plt

#### Merge data from pitchers

In [3]:
path = './Pitching_stats'
files= [file for file in os.listdir(path)]

all_pitchers_data = pd.DataFrame()

for file in files:
    current_data = pd.read_csv(path+'/'+file)
    all_pitchers_data = pd.concat([all_pitchers_data, current_data])

all_pitchers_data.to_csv('all_pitchers_stats.csv', index=False)

In [4]:
all_pitchers = pd.read_csv("all_pitchers_stats.csv")
all_pitchers.head()

,Players,Team,Win,Lost,ERA,Games,GS,CG,SHO,Saves,...,Hits,Runs,ER,HR,HB,BB,SO,WHIP,AVG,Year
0,Pedro Feliciano,NYM,3,6,3.3,92,0,0,0,0,...,66,24,23,1,6,30,56,1.53,0.273,2010
1,Randy Choate,TB,4,3,4.23,85,0,0,0,0,...,41,23,21,3,3,17,40,1.3,0.252,2010
2,Peter Moylan,ATL,6,2,2.97,85,0,0,0,1,...,53,24,21,5,2,37,52,1.41,0.236,2010
3,Nick Masset,CIN,4,4,3.4,82,0,0,0,2,...,64,31,29,7,1,33,85,1.27,0.226,2010
4,Luke Gregerson,SD,4,7,3.22,80,0,0,0,2,...,47,30,28,8,1,18,89,0.83,0.170,2010

#### Task 1: Find the pitcher with the most strikeout

In [5]:
all_pitchers_so = all_pitchers.groupby(by = 'Players').sum()['SO']

In [6]:
pitchers_mostSO = all_pitchers_so.sort_values(ascending=False)

In [7]:
pitchers_mostSO.head(5)

Players
Max Scherzer        2452
Justin Verlander    2260
Clayton Kershaw     2179
Chris Sale          2007
Zack Greinke        1872
Name: SO, dtype: int64

#### Task 2: Find the pitchers with the most saves in every year

In [8]:
#Just change the year column for the year that you want to search
pitchers_year = all_pitchers[all_pitchers['Year'] == 2018]
pitchers_saves_year = pitchers_year.groupby(by = ['Players', 'Team']).sum()['Saves']
pitchers_mostsaves_year = pitchers_saves_year.sort_values(ascending=False)
pitchers_mostsaves_year.head()

Players        Team
Edwin Diaz     SEA     57
Wade Davis     COL     43
Craig Kimbrel  BOS     42
Blake Treinen  OAK     38
Kenley Jansen  LAD     38
Name: Saves, dtype: int64

#### Task 3: Find the pitchers with the most wins

In [10]:
all_pitchers_wins = all_pitchers.sort_values(by = ['Win'], ascending = False)
all_pitchers_wins_group = all_pitchers_wins.groupby('Name').sum()['Win']
all_pitchers_wins.head()

,Players,Team,Win,Lost,ERA,Games,GS,CG,SHO,Saves,...,Hits,Runs,ER,HR,HB,BB,SO,WHIP,AVG,Year
1035,Justin Verlander,DET,24,5,2.40,34,34,4,2,0,...,174,73,67,24,3,57,250,0.92,0.192,2011
3641,Jake Arrieta,CHC,22,6,1.77,33,33,4,3,0,...,150,52,45,10,6,48,236,0.86,0.185,2015
4378,Rick Porcello,BOS,22,4,3.15,33,33,3,0,0,...,193,85,78,23,13,32,189,1.01,0.230,2016
5887,Blake Snell,TB,21,5,1.89,31,31,0,0,0,...,112,41,38,16,1,64,221,0.97,0.178,2018
428,CC Sabathia,NYY,21,7,3.18,34,34,2,0,0,...,209,92,84,20,7,74,197,1.19,0.239,2010